version: '3'

networks:
  wordpress_server:

services:
  wordpress_server:
    container_name: wordpress_server
    build: ./docker/php-apache
    volumes:
      - ./:/var/www/html
      - ./docker/php-apache/logs:/var/log/apache2
    ports:
      - ${APP_PORT}:80
    depends_on:
      - wordpress_mariadb
    networks:
      - wordpress_server
  wordpress_mariadb:
    container_name: mariadb
    build: ./docker/mariadb
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - wordpress_server
  wordpress_phpmyadmin:
    container_name: phpmyadmin
    build: ./docker/phpmyadmin
    ports:
      - ${PMA_WEB_PORT}:80
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - wordpress_mariadb
    networks:
      - wordpress_server
